[@@@js.dummy "!! This code has been generated by gen_js_api !!"]
[@@@ocaml.warning "-7-32-39"]
[@@@ocaml.warning "-7-11-32-33-39"]
open Es2020
open Node_globals
module Internal =
  struct
    module AnonymousInterfaces = struct  end
    module Types = struct open AnonymousInterfaces end
  end
open Internal
open AnonymousInterfaces
open Types
module Constants =
  struct
    include struct include Node_os.Os.Constants.Errno end
    include struct include Node_os.Os.Constants.Priority end
    include struct include Node_os.Os.SignalConstants end
    include struct include Node_crypto.Crypto.Constants end
    include struct include Node_fs.Fs.Constants end
  end
