[@@@js.dummy "!! This code has been generated by gen_js_api !!"]
[@@@ocaml.warning "-7-32-39"]
[@@@ocaml.warning "-7-11-32-33-39"]
open Es5
module Internal =
  struct
    module AnonymousInterfaces = struct  end
    module Types =
      struct
        open AnonymousInterfaces
        type _ProtocolCompletionItem = [ `ProtocolCompletionItem ] intf
        let rec _ProtocolCompletionItem_of_js :
          Ojs.t -> _ProtocolCompletionItem = Obj.magic
        and _ProtocolCompletionItem_to_js : _ProtocolCompletionItem -> Ojs.t
          = Obj.magic
      end
  end
open Internal
open AnonymousInterfaces
open Types
module ProtocolCompletionItem =
  struct
    type t = _ProtocolCompletionItem
    let rec t_of_js : Ojs.t -> t =
      fun (x2 : Ojs.t) -> _ProtocolCompletionItem_of_js x2
    and t_to_js : t -> Ojs.t =
      fun (x1 : _ProtocolCompletionItem) -> _ProtocolCompletionItem_to_js x1
    let (get_data : t -> any) =
      fun (x3 : t) -> any_of_js (Ojs.get_prop_ascii (t_to_js x3) "data")
    let (set_data : t -> any -> unit) =
      fun (x4 : t) ->
        fun (x5 : any) ->
          Ojs.set_prop_ascii (t_to_js x4) "data" (any_to_js x5)
    let (get_fromEdit : t -> bool or_undefined) =
      fun (x6 : t) ->
        or_undefined_of_js Ojs.bool_of_js
          (Ojs.get_prop_ascii (t_to_js x6) "fromEdit")
    let (set_fromEdit : t -> bool or_undefined -> unit) =
      fun (x8 : t) ->
        fun (x9 : bool or_undefined) ->
          Ojs.set_prop_ascii (t_to_js x8) "fromEdit"
            (or_undefined_to_js Ojs.bool_to_js x9)
    let (get_documentationFormat : t -> string or_undefined) =
      fun (x11 : t) ->
        or_undefined_of_js Ojs.string_of_js
          (Ojs.get_prop_ascii (t_to_js x11) "documentationFormat")
    let (set_documentationFormat : t -> string or_undefined -> unit) =
      fun (x13 : t) ->
        fun (x14 : string or_undefined) ->
          Ojs.set_prop_ascii (t_to_js x13) "documentationFormat"
            (or_undefined_to_js Ojs.string_to_js x14)
    let (get_originalItemKind : t -> Proto.CompletionItemKind.t or_undefined)
      =
      fun (x16 : t) ->
        or_undefined_of_js Proto.CompletionItemKind.t_of_js
          (Ojs.get_prop_ascii (t_to_js x16) "originalItemKind")
    let (set_originalItemKind :
      t -> Proto.CompletionItemKind.t or_undefined -> unit) =
      fun (x18 : t) ->
        fun (x19 : Proto.CompletionItemKind.t or_undefined) ->
          Ojs.set_prop_ascii (t_to_js x18) "originalItemKind"
            (or_undefined_to_js Proto.CompletionItemKind.t_to_js x19)
    let (get_deprecated : t -> bool or_undefined) =
      fun (x21 : t) ->
        or_undefined_of_js Ojs.bool_of_js
          (Ojs.get_prop_ascii (t_to_js x21) "deprecated")
    let (set_deprecated : t -> bool or_undefined -> unit) =
      fun (x23 : t) ->
        fun (x24 : bool or_undefined) ->
          Ojs.set_prop_ascii (t_to_js x23) "deprecated"
            (or_undefined_to_js Ojs.bool_to_js x24)
    let (get_insertTextMode : t -> Proto.InsertTextMode.t or_undefined) =
      fun (x26 : t) ->
        or_undefined_of_js Proto.InsertTextMode.t_of_js
          (Ojs.get_prop_ascii (t_to_js x26) "insertTextMode")
    let (set_insertTextMode :
      t -> Proto.InsertTextMode.t or_undefined -> unit) =
      fun (x28 : t) ->
        fun (x29 : Proto.InsertTextMode.t or_undefined) ->
          Ojs.set_prop_ascii (t_to_js x28) "insertTextMode"
            (or_undefined_to_js Proto.InsertTextMode.t_to_js x29)
    let (create : label:string -> t) =
      fun ~label:(x31 : string) ->
        t_of_js
          (Ojs.new_obj
             (Ojs.get_prop_ascii Ojs.global "ProtocolCompletionItem")
             [|(Ojs.string_to_js x31)|])
    let (cast : t -> Code.CompletionItem.t) =
      fun (x32 : t) -> Code.CompletionItem.t_of_js (t_to_js x32)
  end
