joo_global_object.__LIB__VSCODE_JSONRPC__IMPORTS = {
  api: require("vscode-jsonrpc/api"),
  cancellation: require("vscode-jsonrpc/cancellation"),
  connection: require("vscode-jsonrpc/connection"),
  disposable: require("vscode-jsonrpc/disposable"),
  encoding: require("vscode-jsonrpc/encoding"),
  events: require("vscode-jsonrpc/events"),
  is: require("vscode-jsonrpc/is"),
  linkedMap: require("vscode-jsonrpc/linkedMap"),
  main: require("vscode-jsonrpc/main"),
  messageBuffer: require("vscode-jsonrpc/messageBuffer"),
  messageReader: require("vscode-jsonrpc/messageReader"),
  messageWriter: require("vscode-jsonrpc/messageWriter"),
  messages: require("vscode-jsonrpc/messages"),
  ral: require("vscode-jsonrpc/ral"),
  ril: require("vscode-jsonrpc/ril"),
  semaphore: require("vscode-jsonrpc/semaphore"),
};
