[@@@js.dummy "!! This code has been generated by gen_js_api !!"]
[@@@ocaml.warning "-7-32-39"]
[@@@ocaml.warning "-7-11-32-33-39"]
open Es2020
module AbstractMessageBuffer =
  struct
    type t = Ojs.t
    let rec t_of_js : Ojs.t -> t = fun (x2 : Ojs.t) -> x2
    and t_to_js : t -> Ojs.t = fun (x1 : Ojs.t) -> x1
    let (get__encoding : t -> any) =
      fun (x3 : t) -> any_of_js (Ojs.get_prop_ascii (t_to_js x3) "_encoding")
    let (set__encoding : t -> any -> unit) =
      fun (x4 : t) ->
        fun (x5 : any) ->
          Ojs.set_prop_ascii (t_to_js x4) "_encoding" (any_to_js x5)
    let (get__chunks : t -> any) =
      fun (x6 : t) -> any_of_js (Ojs.get_prop_ascii (t_to_js x6) "_chunks")
    let (set__chunks : t -> any -> unit) =
      fun (x7 : t) ->
        fun (x8 : any) ->
          Ojs.set_prop_ascii (t_to_js x7) "_chunks" (any_to_js x8)
    let (get_total_length : t -> any) =
      fun (x9 : t) ->
        any_of_js (Ojs.get_prop_ascii (t_to_js x9) "_totalLength")
    let (set_total_length : t -> any -> unit) =
      fun (x10 : t) ->
        fun (x11 : any) ->
          Ojs.set_prop_ascii (t_to_js x10) "_totalLength" (any_to_js x11)
    let (create :
      ?encoding:Vscode_jsonrpc_ral.RAL.MessageBufferEncoding.t -> unit -> t)
      =
      fun
        ?encoding:(x12 :
                    Vscode_jsonrpc_ral.RAL.MessageBufferEncoding.t option)
        ->
        fun () ->
          t_of_js
            (Ojs.new_obj_arr
               (Ojs.get_prop_ascii Ojs.global "AbstractMessageBuffer")
               (let x13 =
                  Ojs.new_obj (Ojs.get_prop_ascii Ojs.global "Array") [||] in
                (match x12 with
                 | Some x14 ->
                     ignore
                       (Ojs.call x13 "push"
                          [|(Vscode_jsonrpc_ral.RAL.MessageBufferEncoding.t_to_js
                               x14)|])
                 | None -> ());
                x13))
    let (empty_buffer : t -> Uint8Array.t) =
      fun (x15 : t) ->
        Uint8Array.t_of_js (Ojs.call (t_to_js x15) "emptyBuffer" [||])
    let (from_string :
      t ->
        value:string ->
          encoding:Vscode_jsonrpc_ral.RAL.MessageBufferEncoding.t ->
            Uint8Array.t)
      =
      fun (x18 : t) ->
        fun ~value:(x16 : string) ->
          fun
            ~encoding:(x17 : Vscode_jsonrpc_ral.RAL.MessageBufferEncoding.t)
            ->
            Uint8Array.t_of_js
              (Ojs.call (t_to_js x18) "fromString"
                 [|(Ojs.string_to_js x16);(Vscode_jsonrpc_ral.RAL.MessageBufferEncoding.t_to_js
                                             x17)|])
    let (to_string :
      t ->
        value:Uint8Array.t ->
          encoding:Vscode_jsonrpc_ral.RAL.MessageBufferEncoding.t -> string)
      =
      fun (x21 : t) ->
        fun ~value:(x19 : Uint8Array.t) ->
          fun
            ~encoding:(x20 : Vscode_jsonrpc_ral.RAL.MessageBufferEncoding.t)
            ->
            Ojs.string_of_js
              (Ojs.call (t_to_js x21) "toString"
                 [|(Uint8Array.t_to_js x19);(Vscode_jsonrpc_ral.RAL.MessageBufferEncoding.t_to_js
                                               x20)|])
    let (as_native :
      t -> buffer:Uint8Array.t -> ?length:int -> unit -> Uint8Array.t) =
      fun (x26 : t) ->
        fun ~buffer:(x22 : Uint8Array.t) ->
          fun ?length:(x23 : int option) ->
            fun () ->
              Uint8Array.t_of_js
                (let x27 = t_to_js x26 in
                 Ojs.call (Ojs.get_prop_ascii x27 "asNative") "apply"
                   [|x27;((let x24 =
                             Ojs.new_obj
                               (Ojs.get_prop_ascii Ojs.global "Array") 
                               [||] in
                           ignore
                             (Ojs.call x24 "push"
                                [|(Uint8Array.t_to_js x22)|]);
                           (match x23 with
                            | Some x25 ->
                                ignore
                                  (Ojs.call x24 "push"
                                     [|(Ojs.int_to_js x25)|])
                            | None -> ());
                           x24))|])
    let (alloc_native : t -> length:int -> Uint8Array.t) =
      fun (x29 : t) ->
        fun ~length:(x28 : int) ->
          Uint8Array.t_of_js
            (Ojs.call (t_to_js x29) "allocNative" [|(Ojs.int_to_js x28)|])
    let (get_encoding : t -> Vscode_jsonrpc_ral.RAL.MessageBufferEncoding.t)
      =
      fun (x30 : t) ->
        Vscode_jsonrpc_ral.RAL.MessageBufferEncoding.t_of_js
          (Ojs.get_prop_ascii (t_to_js x30) "encoding")
    let (append : t -> chunk:Uint8Array.t or_string -> unit) =
      fun (x33 : t) ->
        fun ~chunk:(x31 : Uint8Array.t or_string) ->
          ignore
            (Ojs.call (t_to_js x33) "append"
               [|(or_string_to_js Uint8Array.t_to_js x31)|])
    let (try_read_headers : t -> (string, string) Map.t or_undefined) =
      fun (x34 : t) ->
        or_undefined_of_js
          (fun (x35 : Ojs.t) ->
             Map.t_of_js Ojs.string_of_js Ojs.string_of_js x35)
          (Ojs.call (t_to_js x34) "tryReadHeaders" [||])
    let (try_read_body : t -> length:int -> Uint8Array.t or_undefined) =
      fun (x39 : t) ->
        fun ~length:(x38 : int) ->
          or_undefined_of_js Uint8Array.t_of_js
            (Ojs.call (t_to_js x39) "tryReadBody" [|(Ojs.int_to_js x38)|])
    let (get_number_of_bytes : t -> int) =
      fun (x41 : t) ->
        Ojs.int_of_js (Ojs.get_prop_ascii (t_to_js x41) "numberOfBytes")
    let (get__read : t -> any) =
      fun (x42 : t) -> any_of_js (Ojs.get_prop_ascii (t_to_js x42) "_read")
    let (set__read : t -> any -> unit) =
      fun (x43 : t) ->
        fun (x44 : any) ->
          Ojs.set_prop_ascii (t_to_js x43) "_read" (any_to_js x44)
    let (cast : t -> Vscode_jsonrpc_ral.RAL.MessageBuffer.t) =
      fun (x45 : t) ->
        Vscode_jsonrpc_ral.RAL.MessageBuffer.t_of_js (t_to_js x45)
  end
