[@@@js.dummy "!! This code has been generated by gen_js_api !!"]
[@@@ocaml.warning "-7-32-39"]
[@@@ocaml.warning "-7-11-32-33-39"]
open Es5
module Promise =
  struct
    include struct include Promise end
    let (create :
      (resolve:('T -> unit) -> reject:('E -> unit) -> unit) -> 'T Promise.t)
      =
      fun (x1 : resolve:('T -> unit) -> reject:('E -> unit) -> unit) ->
        Promise.t_of_js Obj.magic
          (Ojs.new_obj (Ojs.get_prop_ascii Ojs.global "Promise")
             [|(Ojs.fun_to_js 2
                  (fun (x2 : Ojs.t) ->
                     fun (x4 : Ojs.t) ->
                       x1
                         ~resolve:(fun (x3 : 'T) ->
                                     ignore (Ojs.apply x2 [|(Obj.magic x3)|]))
                         ~reject:(fun (x5 : 'E) ->
                                    ignore (Ojs.apply x4 [|(Obj.magic x5)|]))))|])
    let (all : 'T1 Promise.t list -> 'T1 list Promise.t) =
      fun (x7 : 'T1 Promise.t list) ->
        Promise.t_of_js (fun (x10 : Ojs.t) -> Ojs.list_of_js Obj.magic x10)
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "all"
             [|(Ojs.list_to_js
                  (fun (x8 : 'T1 Promise.t) -> Promise.t_to_js Obj.magic x8)
                  x7)|])
    let (all10 :
      ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t * 'T5
        Promise.t * 'T6 Promise.t * 'T7 Promise.t * 'T8 Promise.t * 'T9
        Promise.t * 'T10 Promise.t) ->
        ('T1 * 'T2 * 'T3 * 'T4 * 'T5 * 'T6 * 'T7 * 'T8 * 'T9 * 'T10)
          Promise.t)
      =
      fun
        (x12 :
          ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t *
            'T5 Promise.t * 'T6 Promise.t * 'T7 Promise.t * 'T8 Promise.t *
            'T9 Promise.t * 'T10 Promise.t))
        ->
        Promise.t_of_js
          (fun (x34 : Ojs.t) ->
             let x35 = x34 in
             ((Obj.magic (Ojs.array_get x35 0)),
               (Obj.magic (Ojs.array_get x35 1)),
               (Obj.magic (Ojs.array_get x35 2)),
               (Obj.magic (Ojs.array_get x35 3)),
               (Obj.magic (Ojs.array_get x35 4)),
               (Obj.magic (Ojs.array_get x35 5)),
               (Obj.magic (Ojs.array_get x35 6)),
               (Obj.magic (Ojs.array_get x35 7)),
               (Obj.magic (Ojs.array_get x35 8)),
               (Obj.magic (Ojs.array_get x35 9))))
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "all"
             [|((let (x13, x14, x15, x16, x17, x18, x19, x20, x21, x22) = x12 in
                 let x23 = Ojs.array_make 10 in
                 Ojs.array_set x23 0 (Promise.t_to_js Obj.magic x13);
                 Ojs.array_set x23 1 (Promise.t_to_js Obj.magic x14);
                 Ojs.array_set x23 2 (Promise.t_to_js Obj.magic x15);
                 Ojs.array_set x23 3 (Promise.t_to_js Obj.magic x16);
                 Ojs.array_set x23 4 (Promise.t_to_js Obj.magic x17);
                 Ojs.array_set x23 5 (Promise.t_to_js Obj.magic x18);
                 Ojs.array_set x23 6 (Promise.t_to_js Obj.magic x19);
                 Ojs.array_set x23 7 (Promise.t_to_js Obj.magic x20);
                 Ojs.array_set x23 8 (Promise.t_to_js Obj.magic x21);
                 Ojs.array_set x23 9 (Promise.t_to_js Obj.magic x22);
                 x23))|])
    let (all9 :
      ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t * 'T5
        Promise.t * 'T6 Promise.t * 'T7 Promise.t * 'T8 Promise.t * 'T9
        Promise.t) ->
        ('T1 * 'T2 * 'T3 * 'T4 * 'T5 * 'T6 * 'T7 * 'T8 * 'T9) Promise.t)
      =
      fun
        (x36 :
          ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t *
            'T5 Promise.t * 'T6 Promise.t * 'T7 Promise.t * 'T8 Promise.t *
            'T9 Promise.t))
        ->
        Promise.t_of_js
          (fun (x56 : Ojs.t) ->
             let x57 = x56 in
             ((Obj.magic (Ojs.array_get x57 0)),
               (Obj.magic (Ojs.array_get x57 1)),
               (Obj.magic (Ojs.array_get x57 2)),
               (Obj.magic (Ojs.array_get x57 3)),
               (Obj.magic (Ojs.array_get x57 4)),
               (Obj.magic (Ojs.array_get x57 5)),
               (Obj.magic (Ojs.array_get x57 6)),
               (Obj.magic (Ojs.array_get x57 7)),
               (Obj.magic (Ojs.array_get x57 8))))
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "all"
             [|((let (x37, x38, x39, x40, x41, x42, x43, x44, x45) = x36 in
                 let x46 = Ojs.array_make 9 in
                 Ojs.array_set x46 0 (Promise.t_to_js Obj.magic x37);
                 Ojs.array_set x46 1 (Promise.t_to_js Obj.magic x38);
                 Ojs.array_set x46 2 (Promise.t_to_js Obj.magic x39);
                 Ojs.array_set x46 3 (Promise.t_to_js Obj.magic x40);
                 Ojs.array_set x46 4 (Promise.t_to_js Obj.magic x41);
                 Ojs.array_set x46 5 (Promise.t_to_js Obj.magic x42);
                 Ojs.array_set x46 6 (Promise.t_to_js Obj.magic x43);
                 Ojs.array_set x46 7 (Promise.t_to_js Obj.magic x44);
                 Ojs.array_set x46 8 (Promise.t_to_js Obj.magic x45);
                 x46))|])
    let (all8 :
      ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t * 'T5
        Promise.t * 'T6 Promise.t * 'T7 Promise.t * 'T8 Promise.t) ->
        ('T1 * 'T2 * 'T3 * 'T4 * 'T5 * 'T6 * 'T7 * 'T8) Promise.t)
      =
      fun
        (x58 :
          ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t *
            'T5 Promise.t * 'T6 Promise.t * 'T7 Promise.t * 'T8 Promise.t))
        ->
        Promise.t_of_js
          (fun (x76 : Ojs.t) ->
             let x77 = x76 in
             ((Obj.magic (Ojs.array_get x77 0)),
               (Obj.magic (Ojs.array_get x77 1)),
               (Obj.magic (Ojs.array_get x77 2)),
               (Obj.magic (Ojs.array_get x77 3)),
               (Obj.magic (Ojs.array_get x77 4)),
               (Obj.magic (Ojs.array_get x77 5)),
               (Obj.magic (Ojs.array_get x77 6)),
               (Obj.magic (Ojs.array_get x77 7))))
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "all"
             [|((let (x59, x60, x61, x62, x63, x64, x65, x66) = x58 in
                 let x67 = Ojs.array_make 8 in
                 Ojs.array_set x67 0 (Promise.t_to_js Obj.magic x59);
                 Ojs.array_set x67 1 (Promise.t_to_js Obj.magic x60);
                 Ojs.array_set x67 2 (Promise.t_to_js Obj.magic x61);
                 Ojs.array_set x67 3 (Promise.t_to_js Obj.magic x62);
                 Ojs.array_set x67 4 (Promise.t_to_js Obj.magic x63);
                 Ojs.array_set x67 5 (Promise.t_to_js Obj.magic x64);
                 Ojs.array_set x67 6 (Promise.t_to_js Obj.magic x65);
                 Ojs.array_set x67 7 (Promise.t_to_js Obj.magic x66);
                 x67))|])
    let (all7 :
      ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t * 'T5
        Promise.t * 'T6 Promise.t * 'T7 Promise.t) ->
        ('T1 * 'T2 * 'T3 * 'T4 * 'T5 * 'T6 * 'T7) Promise.t)
      =
      fun
        (x78 :
          ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t *
            'T5 Promise.t * 'T6 Promise.t * 'T7 Promise.t))
        ->
        Promise.t_of_js
          (fun (x94 : Ojs.t) ->
             let x95 = x94 in
             ((Obj.magic (Ojs.array_get x95 0)),
               (Obj.magic (Ojs.array_get x95 1)),
               (Obj.magic (Ojs.array_get x95 2)),
               (Obj.magic (Ojs.array_get x95 3)),
               (Obj.magic (Ojs.array_get x95 4)),
               (Obj.magic (Ojs.array_get x95 5)),
               (Obj.magic (Ojs.array_get x95 6))))
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "all"
             [|((let (x79, x80, x81, x82, x83, x84, x85) = x78 in
                 let x86 = Ojs.array_make 7 in
                 Ojs.array_set x86 0 (Promise.t_to_js Obj.magic x79);
                 Ojs.array_set x86 1 (Promise.t_to_js Obj.magic x80);
                 Ojs.array_set x86 2 (Promise.t_to_js Obj.magic x81);
                 Ojs.array_set x86 3 (Promise.t_to_js Obj.magic x82);
                 Ojs.array_set x86 4 (Promise.t_to_js Obj.magic x83);
                 Ojs.array_set x86 5 (Promise.t_to_js Obj.magic x84);
                 Ojs.array_set x86 6 (Promise.t_to_js Obj.magic x85);
                 x86))|])
    let (all6 :
      ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t * 'T5
        Promise.t * 'T6 Promise.t) ->
        ('T1 * 'T2 * 'T3 * 'T4 * 'T5 * 'T6) Promise.t)
      =
      fun
        (x96 :
          ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t *
            'T5 Promise.t * 'T6 Promise.t))
        ->
        Promise.t_of_js
          (fun (x110 : Ojs.t) ->
             let x111 = x110 in
             ((Obj.magic (Ojs.array_get x111 0)),
               (Obj.magic (Ojs.array_get x111 1)),
               (Obj.magic (Ojs.array_get x111 2)),
               (Obj.magic (Ojs.array_get x111 3)),
               (Obj.magic (Ojs.array_get x111 4)),
               (Obj.magic (Ojs.array_get x111 5))))
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "all"
             [|((let (x97, x98, x99, x100, x101, x102) = x96 in
                 let x103 = Ojs.array_make 6 in
                 Ojs.array_set x103 0 (Promise.t_to_js Obj.magic x97);
                 Ojs.array_set x103 1 (Promise.t_to_js Obj.magic x98);
                 Ojs.array_set x103 2 (Promise.t_to_js Obj.magic x99);
                 Ojs.array_set x103 3 (Promise.t_to_js Obj.magic x100);
                 Ojs.array_set x103 4 (Promise.t_to_js Obj.magic x101);
                 Ojs.array_set x103 5 (Promise.t_to_js Obj.magic x102);
                 x103))|])
    let (all5 :
      ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t * 'T5
        Promise.t) -> ('T1 * 'T2 * 'T3 * 'T4 * 'T5) Promise.t)
      =
      fun
        (x112 :
          ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t *
            'T5 Promise.t))
        ->
        Promise.t_of_js
          (fun (x124 : Ojs.t) ->
             let x125 = x124 in
             ((Obj.magic (Ojs.array_get x125 0)),
               (Obj.magic (Ojs.array_get x125 1)),
               (Obj.magic (Ojs.array_get x125 2)),
               (Obj.magic (Ojs.array_get x125 3)),
               (Obj.magic (Ojs.array_get x125 4))))
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "all"
             [|((let (x113, x114, x115, x116, x117) = x112 in
                 let x118 = Ojs.array_make 5 in
                 Ojs.array_set x118 0 (Promise.t_to_js Obj.magic x113);
                 Ojs.array_set x118 1 (Promise.t_to_js Obj.magic x114);
                 Ojs.array_set x118 2 (Promise.t_to_js Obj.magic x115);
                 Ojs.array_set x118 3 (Promise.t_to_js Obj.magic x116);
                 Ojs.array_set x118 4 (Promise.t_to_js Obj.magic x117);
                 x118))|])
    let (all4 :
      ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t) ->
        ('T1 * 'T2 * 'T3 * 'T4) Promise.t)
      =
      fun
        (x126 :
          ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t))
        ->
        Promise.t_of_js
          (fun (x136 : Ojs.t) ->
             let x137 = x136 in
             ((Obj.magic (Ojs.array_get x137 0)),
               (Obj.magic (Ojs.array_get x137 1)),
               (Obj.magic (Ojs.array_get x137 2)),
               (Obj.magic (Ojs.array_get x137 3))))
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "all"
             [|((let (x127, x128, x129, x130) = x126 in
                 let x131 = Ojs.array_make 4 in
                 Ojs.array_set x131 0 (Promise.t_to_js Obj.magic x127);
                 Ojs.array_set x131 1 (Promise.t_to_js Obj.magic x128);
                 Ojs.array_set x131 2 (Promise.t_to_js Obj.magic x129);
                 Ojs.array_set x131 3 (Promise.t_to_js Obj.magic x130);
                 x131))|])
    let (all3 :
      ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t) ->
        ('T1 * 'T2 * 'T3) Promise.t)
      =
      fun (x138 : ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t)) ->
        Promise.t_of_js
          (fun (x146 : Ojs.t) ->
             let x147 = x146 in
             ((Obj.magic (Ojs.array_get x147 0)),
               (Obj.magic (Ojs.array_get x147 1)),
               (Obj.magic (Ojs.array_get x147 2))))
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "all"
             [|((let (x139, x140, x141) = x138 in
                 let x142 = Ojs.array_make 3 in
                 Ojs.array_set x142 0 (Promise.t_to_js Obj.magic x139);
                 Ojs.array_set x142 1 (Promise.t_to_js Obj.magic x140);
                 Ojs.array_set x142 2 (Promise.t_to_js Obj.magic x141);
                 x142))|])
    let (all2 : ('T1 Promise.t * 'T2 Promise.t) -> ('T1 * 'T2) Promise.t) =
      fun (x148 : ('T1 Promise.t * 'T2 Promise.t)) ->
        Promise.t_of_js
          (fun (x154 : Ojs.t) ->
             let x155 = x154 in
             ((Obj.magic (Ojs.array_get x155 0)),
               (Obj.magic (Ojs.array_get x155 1))))
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "all"
             [|((let (x149, x150) = x148 in
                 let x151 = Ojs.array_make 2 in
                 Ojs.array_set x151 0 (Promise.t_to_js Obj.magic x149);
                 Ojs.array_set x151 1 (Promise.t_to_js Obj.magic x150);
                 x151))|])
    let (all1 : 'T Promise.t list -> 'T list Promise.t) =
      fun (x156 : 'T Promise.t list) ->
        Promise.t_of_js (fun (x159 : Ojs.t) -> Ojs.list_of_js Obj.magic x159)
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "all"
             [|(Ojs.list_to_js
                  (fun (x157 : 'T Promise.t) ->
                     Promise.t_to_js Obj.magic x157) x156)|])
    let (race : 'T list -> any Promise.t) =
      fun (x161 : 'T list) ->
        Promise.t_of_js any_of_js
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "race"
             [|(Ojs.list_to_js Obj.magic x161)|])
    let (reject : 'E -> 'T Promise.t) =
      fun (x164 : 'E) ->
        Promise.t_of_js Obj.magic
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "reject"
             [|(Obj.magic x164)|])
    let (resolve : 'T -> 'T Promise.t) =
      fun (x166 : 'T) ->
        Promise.t_of_js Obj.magic
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "resolve"
             [|(Obj.magic x166)|])
  end
module PromiseConstructor =
  struct
    type t = Ojs.t
    let rec t_of_js : Ojs.t -> t = fun (x169 : Ojs.t) -> x169
    and t_to_js : t -> Ojs.t = fun (x168 : Ojs.t) -> x168
    let (get_prototype : t -> any Promise.t) =
      fun (x170 : t) ->
        Promise.t_of_js any_of_js
          (Ojs.get_prop_ascii (t_to_js x170) "prototype")
    let (create :
      t ->
        (resolve:('T -> unit) -> reject:('E -> unit) -> unit) -> 'T Promise.t)
      =
      fun (x177 : t) ->
        fun (x172 : resolve:('T -> unit) -> reject:('E -> unit) -> unit) ->
          Promise.t_of_js Obj.magic
            (Ojs.new_obj (t_to_js x177)
               [|(Ojs.fun_to_js 2
                    (fun (x173 : Ojs.t) ->
                       fun (x175 : Ojs.t) ->
                         x172
                           ~resolve:(fun (x174 : 'T) ->
                                       ignore
                                         (Ojs.apply x173 [|(Obj.magic x174)|]))
                           ~reject:(fun (x176 : 'E) ->
                                      ignore
                                        (Ojs.apply x175 [|(Obj.magic x176)|]))))|])
    let (all : t -> 'T1 Promise.t list -> 'T1 list Promise.t) =
      fun (x182 : t) ->
        fun (x179 : 'T1 Promise.t list) ->
          Promise.t_of_js
            (fun (x183 : Ojs.t) -> Ojs.list_of_js Obj.magic x183)
            (Ojs.call (t_to_js x182) "all"
               [|(Ojs.list_to_js
                    (fun (x180 : 'T1 Promise.t) ->
                       Promise.t_to_js Obj.magic x180) x179)|])
    let (all10 :
      t ->
        ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t * 'T5
          Promise.t * 'T6 Promise.t * 'T7 Promise.t * 'T8 Promise.t * 'T9
          Promise.t * 'T10 Promise.t) ->
          ('T1 * 'T2 * 'T3 * 'T4 * 'T5 * 'T6 * 'T7 * 'T8 * 'T9 * 'T10)
            Promise.t)
      =
      fun (x207 : t) ->
        fun
          (x185 :
            ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t *
              'T5 Promise.t * 'T6 Promise.t * 'T7 Promise.t * 'T8 Promise.t *
              'T9 Promise.t * 'T10 Promise.t))
          ->
          Promise.t_of_js
            (fun (x208 : Ojs.t) ->
               let x209 = x208 in
               ((Obj.magic (Ojs.array_get x209 0)),
                 (Obj.magic (Ojs.array_get x209 1)),
                 (Obj.magic (Ojs.array_get x209 2)),
                 (Obj.magic (Ojs.array_get x209 3)),
                 (Obj.magic (Ojs.array_get x209 4)),
                 (Obj.magic (Ojs.array_get x209 5)),
                 (Obj.magic (Ojs.array_get x209 6)),
                 (Obj.magic (Ojs.array_get x209 7)),
                 (Obj.magic (Ojs.array_get x209 8)),
                 (Obj.magic (Ojs.array_get x209 9))))
            (Ojs.call (t_to_js x207) "all"
               [|((let (x186, x187, x188, x189, x190, x191, x192, x193, x194,
                        x195)
                     = x185 in
                   let x196 = Ojs.array_make 10 in
                   Ojs.array_set x196 0 (Promise.t_to_js Obj.magic x186);
                   Ojs.array_set x196 1 (Promise.t_to_js Obj.magic x187);
                   Ojs.array_set x196 2 (Promise.t_to_js Obj.magic x188);
                   Ojs.array_set x196 3 (Promise.t_to_js Obj.magic x189);
                   Ojs.array_set x196 4 (Promise.t_to_js Obj.magic x190);
                   Ojs.array_set x196 5 (Promise.t_to_js Obj.magic x191);
                   Ojs.array_set x196 6 (Promise.t_to_js Obj.magic x192);
                   Ojs.array_set x196 7 (Promise.t_to_js Obj.magic x193);
                   Ojs.array_set x196 8 (Promise.t_to_js Obj.magic x194);
                   Ojs.array_set x196 9 (Promise.t_to_js Obj.magic x195);
                   x196))|])
    let (all9 :
      t ->
        ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t * 'T5
          Promise.t * 'T6 Promise.t * 'T7 Promise.t * 'T8 Promise.t * 'T9
          Promise.t) ->
          ('T1 * 'T2 * 'T3 * 'T4 * 'T5 * 'T6 * 'T7 * 'T8 * 'T9) Promise.t)
      =
      fun (x230 : t) ->
        fun
          (x210 :
            ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t *
              'T5 Promise.t * 'T6 Promise.t * 'T7 Promise.t * 'T8 Promise.t *
              'T9 Promise.t))
          ->
          Promise.t_of_js
            (fun (x231 : Ojs.t) ->
               let x232 = x231 in
               ((Obj.magic (Ojs.array_get x232 0)),
                 (Obj.magic (Ojs.array_get x232 1)),
                 (Obj.magic (Ojs.array_get x232 2)),
                 (Obj.magic (Ojs.array_get x232 3)),
                 (Obj.magic (Ojs.array_get x232 4)),
                 (Obj.magic (Ojs.array_get x232 5)),
                 (Obj.magic (Ojs.array_get x232 6)),
                 (Obj.magic (Ojs.array_get x232 7)),
                 (Obj.magic (Ojs.array_get x232 8))))
            (Ojs.call (t_to_js x230) "all"
               [|((let (x211, x212, x213, x214, x215, x216, x217, x218, x219)
                     = x210 in
                   let x220 = Ojs.array_make 9 in
                   Ojs.array_set x220 0 (Promise.t_to_js Obj.magic x211);
                   Ojs.array_set x220 1 (Promise.t_to_js Obj.magic x212);
                   Ojs.array_set x220 2 (Promise.t_to_js Obj.magic x213);
                   Ojs.array_set x220 3 (Promise.t_to_js Obj.magic x214);
                   Ojs.array_set x220 4 (Promise.t_to_js Obj.magic x215);
                   Ojs.array_set x220 5 (Promise.t_to_js Obj.magic x216);
                   Ojs.array_set x220 6 (Promise.t_to_js Obj.magic x217);
                   Ojs.array_set x220 7 (Promise.t_to_js Obj.magic x218);
                   Ojs.array_set x220 8 (Promise.t_to_js Obj.magic x219);
                   x220))|])
    let (all8 :
      t ->
        ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t * 'T5
          Promise.t * 'T6 Promise.t * 'T7 Promise.t * 'T8 Promise.t) ->
          ('T1 * 'T2 * 'T3 * 'T4 * 'T5 * 'T6 * 'T7 * 'T8) Promise.t)
      =
      fun (x251 : t) ->
        fun
          (x233 :
            ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t *
              'T5 Promise.t * 'T6 Promise.t * 'T7 Promise.t * 'T8 Promise.t))
          ->
          Promise.t_of_js
            (fun (x252 : Ojs.t) ->
               let x253 = x252 in
               ((Obj.magic (Ojs.array_get x253 0)),
                 (Obj.magic (Ojs.array_get x253 1)),
                 (Obj.magic (Ojs.array_get x253 2)),
                 (Obj.magic (Ojs.array_get x253 3)),
                 (Obj.magic (Ojs.array_get x253 4)),
                 (Obj.magic (Ojs.array_get x253 5)),
                 (Obj.magic (Ojs.array_get x253 6)),
                 (Obj.magic (Ojs.array_get x253 7))))
            (Ojs.call (t_to_js x251) "all"
               [|((let (x234, x235, x236, x237, x238, x239, x240, x241) =
                     x233 in
                   let x242 = Ojs.array_make 8 in
                   Ojs.array_set x242 0 (Promise.t_to_js Obj.magic x234);
                   Ojs.array_set x242 1 (Promise.t_to_js Obj.magic x235);
                   Ojs.array_set x242 2 (Promise.t_to_js Obj.magic x236);
                   Ojs.array_set x242 3 (Promise.t_to_js Obj.magic x237);
                   Ojs.array_set x242 4 (Promise.t_to_js Obj.magic x238);
                   Ojs.array_set x242 5 (Promise.t_to_js Obj.magic x239);
                   Ojs.array_set x242 6 (Promise.t_to_js Obj.magic x240);
                   Ojs.array_set x242 7 (Promise.t_to_js Obj.magic x241);
                   x242))|])
    let (all7 :
      t ->
        ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t * 'T5
          Promise.t * 'T6 Promise.t * 'T7 Promise.t) ->
          ('T1 * 'T2 * 'T3 * 'T4 * 'T5 * 'T6 * 'T7) Promise.t)
      =
      fun (x270 : t) ->
        fun
          (x254 :
            ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t *
              'T5 Promise.t * 'T6 Promise.t * 'T7 Promise.t))
          ->
          Promise.t_of_js
            (fun (x271 : Ojs.t) ->
               let x272 = x271 in
               ((Obj.magic (Ojs.array_get x272 0)),
                 (Obj.magic (Ojs.array_get x272 1)),
                 (Obj.magic (Ojs.array_get x272 2)),
                 (Obj.magic (Ojs.array_get x272 3)),
                 (Obj.magic (Ojs.array_get x272 4)),
                 (Obj.magic (Ojs.array_get x272 5)),
                 (Obj.magic (Ojs.array_get x272 6))))
            (Ojs.call (t_to_js x270) "all"
               [|((let (x255, x256, x257, x258, x259, x260, x261) = x254 in
                   let x262 = Ojs.array_make 7 in
                   Ojs.array_set x262 0 (Promise.t_to_js Obj.magic x255);
                   Ojs.array_set x262 1 (Promise.t_to_js Obj.magic x256);
                   Ojs.array_set x262 2 (Promise.t_to_js Obj.magic x257);
                   Ojs.array_set x262 3 (Promise.t_to_js Obj.magic x258);
                   Ojs.array_set x262 4 (Promise.t_to_js Obj.magic x259);
                   Ojs.array_set x262 5 (Promise.t_to_js Obj.magic x260);
                   Ojs.array_set x262 6 (Promise.t_to_js Obj.magic x261);
                   x262))|])
    let (all6 :
      t ->
        ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t * 'T5
          Promise.t * 'T6 Promise.t) ->
          ('T1 * 'T2 * 'T3 * 'T4 * 'T5 * 'T6) Promise.t)
      =
      fun (x287 : t) ->
        fun
          (x273 :
            ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t *
              'T5 Promise.t * 'T6 Promise.t))
          ->
          Promise.t_of_js
            (fun (x288 : Ojs.t) ->
               let x289 = x288 in
               ((Obj.magic (Ojs.array_get x289 0)),
                 (Obj.magic (Ojs.array_get x289 1)),
                 (Obj.magic (Ojs.array_get x289 2)),
                 (Obj.magic (Ojs.array_get x289 3)),
                 (Obj.magic (Ojs.array_get x289 4)),
                 (Obj.magic (Ojs.array_get x289 5))))
            (Ojs.call (t_to_js x287) "all"
               [|((let (x274, x275, x276, x277, x278, x279) = x273 in
                   let x280 = Ojs.array_make 6 in
                   Ojs.array_set x280 0 (Promise.t_to_js Obj.magic x274);
                   Ojs.array_set x280 1 (Promise.t_to_js Obj.magic x275);
                   Ojs.array_set x280 2 (Promise.t_to_js Obj.magic x276);
                   Ojs.array_set x280 3 (Promise.t_to_js Obj.magic x277);
                   Ojs.array_set x280 4 (Promise.t_to_js Obj.magic x278);
                   Ojs.array_set x280 5 (Promise.t_to_js Obj.magic x279);
                   x280))|])
    let (all5 :
      t ->
        ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t * 'T5
          Promise.t) -> ('T1 * 'T2 * 'T3 * 'T4 * 'T5) Promise.t)
      =
      fun (x302 : t) ->
        fun
          (x290 :
            ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t *
              'T5 Promise.t))
          ->
          Promise.t_of_js
            (fun (x303 : Ojs.t) ->
               let x304 = x303 in
               ((Obj.magic (Ojs.array_get x304 0)),
                 (Obj.magic (Ojs.array_get x304 1)),
                 (Obj.magic (Ojs.array_get x304 2)),
                 (Obj.magic (Ojs.array_get x304 3)),
                 (Obj.magic (Ojs.array_get x304 4))))
            (Ojs.call (t_to_js x302) "all"
               [|((let (x291, x292, x293, x294, x295) = x290 in
                   let x296 = Ojs.array_make 5 in
                   Ojs.array_set x296 0 (Promise.t_to_js Obj.magic x291);
                   Ojs.array_set x296 1 (Promise.t_to_js Obj.magic x292);
                   Ojs.array_set x296 2 (Promise.t_to_js Obj.magic x293);
                   Ojs.array_set x296 3 (Promise.t_to_js Obj.magic x294);
                   Ojs.array_set x296 4 (Promise.t_to_js Obj.magic x295);
                   x296))|])
    let (all4 :
      t ->
        ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t) ->
          ('T1 * 'T2 * 'T3 * 'T4) Promise.t)
      =
      fun (x315 : t) ->
        fun
          (x305 :
            ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t))
          ->
          Promise.t_of_js
            (fun (x316 : Ojs.t) ->
               let x317 = x316 in
               ((Obj.magic (Ojs.array_get x317 0)),
                 (Obj.magic (Ojs.array_get x317 1)),
                 (Obj.magic (Ojs.array_get x317 2)),
                 (Obj.magic (Ojs.array_get x317 3))))
            (Ojs.call (t_to_js x315) "all"
               [|((let (x306, x307, x308, x309) = x305 in
                   let x310 = Ojs.array_make 4 in
                   Ojs.array_set x310 0 (Promise.t_to_js Obj.magic x306);
                   Ojs.array_set x310 1 (Promise.t_to_js Obj.magic x307);
                   Ojs.array_set x310 2 (Promise.t_to_js Obj.magic x308);
                   Ojs.array_set x310 3 (Promise.t_to_js Obj.magic x309);
                   x310))|])
    let (all3 :
      t ->
        ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t) ->
          ('T1 * 'T2 * 'T3) Promise.t)
      =
      fun (x326 : t) ->
        fun (x318 : ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t)) ->
          Promise.t_of_js
            (fun (x327 : Ojs.t) ->
               let x328 = x327 in
               ((Obj.magic (Ojs.array_get x328 0)),
                 (Obj.magic (Ojs.array_get x328 1)),
                 (Obj.magic (Ojs.array_get x328 2))))
            (Ojs.call (t_to_js x326) "all"
               [|((let (x319, x320, x321) = x318 in
                   let x322 = Ojs.array_make 3 in
                   Ojs.array_set x322 0 (Promise.t_to_js Obj.magic x319);
                   Ojs.array_set x322 1 (Promise.t_to_js Obj.magic x320);
                   Ojs.array_set x322 2 (Promise.t_to_js Obj.magic x321);
                   x322))|])
    let (all2 :
      t -> ('T1 Promise.t * 'T2 Promise.t) -> ('T1 * 'T2) Promise.t) =
      fun (x335 : t) ->
        fun (x329 : ('T1 Promise.t * 'T2 Promise.t)) ->
          Promise.t_of_js
            (fun (x336 : Ojs.t) ->
               let x337 = x336 in
               ((Obj.magic (Ojs.array_get x337 0)),
                 (Obj.magic (Ojs.array_get x337 1))))
            (Ojs.call (t_to_js x335) "all"
               [|((let (x330, x331) = x329 in
                   let x332 = Ojs.array_make 2 in
                   Ojs.array_set x332 0 (Promise.t_to_js Obj.magic x330);
                   Ojs.array_set x332 1 (Promise.t_to_js Obj.magic x331);
                   x332))|])
    let (all1 : t -> 'T Promise.t list -> 'T list Promise.t) =
      fun (x341 : t) ->
        fun (x338 : 'T Promise.t list) ->
          Promise.t_of_js
            (fun (x342 : Ojs.t) -> Ojs.list_of_js Obj.magic x342)
            (Ojs.call (t_to_js x341) "all"
               [|(Ojs.list_to_js
                    (fun (x339 : 'T Promise.t) ->
                       Promise.t_to_js Obj.magic x339) x338)|])
    let (race : t -> 'T list -> any Promise.t) =
      fun (x346 : t) ->
        fun (x344 : 'T list) ->
          Promise.t_of_js any_of_js
            (Ojs.call (t_to_js x346) "race"
               [|(Ojs.list_to_js Obj.magic x344)|])
    let (reject : t -> 'E -> 'T Promise.t) =
      fun (x349 : t) ->
        fun (x348 : 'E) ->
          Promise.t_of_js Obj.magic
            (Ojs.call (t_to_js x349) "reject" [|(Obj.magic x348)|])
    let (resolve : t -> unit Promise.t) =
      fun (x351 : t) ->
        Promise.t_of_js Ojs.unit_of_js
          (Ojs.call (t_to_js x351) "resolve" [||])
    let (resolve' : t -> 'T -> 'T Promise.t) =
      fun (x354 : t) ->
        fun (x353 : 'T) ->
          Promise.t_of_js Obj.magic
            (Ojs.call (t_to_js x354) "resolve" [|(Obj.magic x353)|])
  end
let (promise : PromiseConstructor.t) =
  PromiseConstructor.t_of_js (Ojs.get_prop_ascii Ojs.global "Promise")
