[@@@js.dummy "!! This code has been generated by gen_js_api !!"]
[@@@ocaml.warning "-7-32-39"]
[@@@ocaml.warning "-7-11-32-33-39"]
open Es5
module Promise =
  struct
    include struct include Promise end
    let (create :
      (resolve:('T -> unit) -> reject:('E -> unit) -> unit) -> 'T Promise.t)
      =
      fun (x1 : resolve:('T -> unit) -> reject:('E -> unit) -> unit) ->
        Promise.t_of_js Obj.magic
          (Ojs.new_obj (Ojs.get_prop_ascii Ojs.global "Promise")
             [|(Ojs.fun_to_js 2
                  (fun (x2 : Ojs.t) ->
                     fun (x4 : Ojs.t) ->
                       x1
                         ~resolve:(fun (x3 : 'T) ->
                                     ignore (Ojs.apply x2 [|(Obj.magic x3)|]))
                         ~reject:(fun (x5 : 'E) ->
                                    ignore (Ojs.apply x4 [|(Obj.magic x5)|]))))|])
    let (all : 'T1 Promise.t list -> 'T1 list Promise.t) =
      fun (x7 : 'T1 Promise.t list) ->
        Promise.t_of_js (fun (x10 : Ojs.t) -> Ojs.list_of_js Obj.magic x10)
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "all"
             [|(Ojs.list_to_js
                  (fun (x8 : 'T1 Promise.t) -> Promise.t_to_js Obj.magic x8)
                  x7)|])
    let (all10 :
      ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t * 'T5
        Promise.t * 'T6 Promise.t * 'T7 Promise.t * 'T8 Promise.t * 'T9
        Promise.t * 'T10 Promise.t) ->
        ('T1 * 'T2 * 'T3 * 'T4 * 'T5 * 'T6 * 'T7 * 'T8 * 'T9 * 'T10)
          Promise.t)
      =
      fun
        (x12 :
          ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t *
            'T5 Promise.t * 'T6 Promise.t * 'T7 Promise.t * 'T8 Promise.t *
            'T9 Promise.t * 'T10 Promise.t))
        ->
        Promise.t_of_js
          (fun (x34 : Ojs.t) ->
             let x35 = x34 in
             ((Obj.magic (Ojs.array_get x35 0)),
               (Obj.magic (Ojs.array_get x35 1)),
               (Obj.magic (Ojs.array_get x35 2)),
               (Obj.magic (Ojs.array_get x35 3)),
               (Obj.magic (Ojs.array_get x35 4)),
               (Obj.magic (Ojs.array_get x35 5)),
               (Obj.magic (Ojs.array_get x35 6)),
               (Obj.magic (Ojs.array_get x35 7)),
               (Obj.magic (Ojs.array_get x35 8)),
               (Obj.magic (Ojs.array_get x35 9))))
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "all"
             [|((let (x13, x14, x15, x16, x17, x18, x19, x20, x21, x22) = x12 in
                 let x23 = Ojs.array_make 10 in
                 Ojs.array_set x23 0 (Promise.t_to_js Obj.magic x13);
                 Ojs.array_set x23 1 (Promise.t_to_js Obj.magic x14);
                 Ojs.array_set x23 2 (Promise.t_to_js Obj.magic x15);
                 Ojs.array_set x23 3 (Promise.t_to_js Obj.magic x16);
                 Ojs.array_set x23 4 (Promise.t_to_js Obj.magic x17);
                 Ojs.array_set x23 5 (Promise.t_to_js Obj.magic x18);
                 Ojs.array_set x23 6 (Promise.t_to_js Obj.magic x19);
                 Ojs.array_set x23 7 (Promise.t_to_js Obj.magic x20);
                 Ojs.array_set x23 8 (Promise.t_to_js Obj.magic x21);
                 Ojs.array_set x23 9 (Promise.t_to_js Obj.magic x22);
                 x23))|])
    let (all9 :
      ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t * 'T5
        Promise.t * 'T6 Promise.t * 'T7 Promise.t * 'T8 Promise.t * 'T9
        Promise.t) ->
        ('T1 * 'T2 * 'T3 * 'T4 * 'T5 * 'T6 * 'T7 * 'T8 * 'T9) Promise.t)
      =
      fun
        (x36 :
          ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t *
            'T5 Promise.t * 'T6 Promise.t * 'T7 Promise.t * 'T8 Promise.t *
            'T9 Promise.t))
        ->
        Promise.t_of_js
          (fun (x56 : Ojs.t) ->
             let x57 = x56 in
             ((Obj.magic (Ojs.array_get x57 0)),
               (Obj.magic (Ojs.array_get x57 1)),
               (Obj.magic (Ojs.array_get x57 2)),
               (Obj.magic (Ojs.array_get x57 3)),
               (Obj.magic (Ojs.array_get x57 4)),
               (Obj.magic (Ojs.array_get x57 5)),
               (Obj.magic (Ojs.array_get x57 6)),
               (Obj.magic (Ojs.array_get x57 7)),
               (Obj.magic (Ojs.array_get x57 8))))
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "all"
             [|((let (x37, x38, x39, x40, x41, x42, x43, x44, x45) = x36 in
                 let x46 = Ojs.array_make 9 in
                 Ojs.array_set x46 0 (Promise.t_to_js Obj.magic x37);
                 Ojs.array_set x46 1 (Promise.t_to_js Obj.magic x38);
                 Ojs.array_set x46 2 (Promise.t_to_js Obj.magic x39);
                 Ojs.array_set x46 3 (Promise.t_to_js Obj.magic x40);
                 Ojs.array_set x46 4 (Promise.t_to_js Obj.magic x41);
                 Ojs.array_set x46 5 (Promise.t_to_js Obj.magic x42);
                 Ojs.array_set x46 6 (Promise.t_to_js Obj.magic x43);
                 Ojs.array_set x46 7 (Promise.t_to_js Obj.magic x44);
                 Ojs.array_set x46 8 (Promise.t_to_js Obj.magic x45);
                 x46))|])
    let (all8 :
      ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t * 'T5
        Promise.t * 'T6 Promise.t * 'T7 Promise.t * 'T8 Promise.t) ->
        ('T1 * 'T2 * 'T3 * 'T4 * 'T5 * 'T6 * 'T7 * 'T8) Promise.t)
      =
      fun
        (x58 :
          ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t *
            'T5 Promise.t * 'T6 Promise.t * 'T7 Promise.t * 'T8 Promise.t))
        ->
        Promise.t_of_js
          (fun (x76 : Ojs.t) ->
             let x77 = x76 in
             ((Obj.magic (Ojs.array_get x77 0)),
               (Obj.magic (Ojs.array_get x77 1)),
               (Obj.magic (Ojs.array_get x77 2)),
               (Obj.magic (Ojs.array_get x77 3)),
               (Obj.magic (Ojs.array_get x77 4)),
               (Obj.magic (Ojs.array_get x77 5)),
               (Obj.magic (Ojs.array_get x77 6)),
               (Obj.magic (Ojs.array_get x77 7))))
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "all"
             [|((let (x59, x60, x61, x62, x63, x64, x65, x66) = x58 in
                 let x67 = Ojs.array_make 8 in
                 Ojs.array_set x67 0 (Promise.t_to_js Obj.magic x59);
                 Ojs.array_set x67 1 (Promise.t_to_js Obj.magic x60);
                 Ojs.array_set x67 2 (Promise.t_to_js Obj.magic x61);
                 Ojs.array_set x67 3 (Promise.t_to_js Obj.magic x62);
                 Ojs.array_set x67 4 (Promise.t_to_js Obj.magic x63);
                 Ojs.array_set x67 5 (Promise.t_to_js Obj.magic x64);
                 Ojs.array_set x67 6 (Promise.t_to_js Obj.magic x65);
                 Ojs.array_set x67 7 (Promise.t_to_js Obj.magic x66);
                 x67))|])
    let (all7 :
      ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t * 'T5
        Promise.t * 'T6 Promise.t * 'T7 Promise.t) ->
        ('T1 * 'T2 * 'T3 * 'T4 * 'T5 * 'T6 * 'T7) Promise.t)
      =
      fun
        (x78 :
          ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t *
            'T5 Promise.t * 'T6 Promise.t * 'T7 Promise.t))
        ->
        Promise.t_of_js
          (fun (x94 : Ojs.t) ->
             let x95 = x94 in
             ((Obj.magic (Ojs.array_get x95 0)),
               (Obj.magic (Ojs.array_get x95 1)),
               (Obj.magic (Ojs.array_get x95 2)),
               (Obj.magic (Ojs.array_get x95 3)),
               (Obj.magic (Ojs.array_get x95 4)),
               (Obj.magic (Ojs.array_get x95 5)),
               (Obj.magic (Ojs.array_get x95 6))))
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "all"
             [|((let (x79, x80, x81, x82, x83, x84, x85) = x78 in
                 let x86 = Ojs.array_make 7 in
                 Ojs.array_set x86 0 (Promise.t_to_js Obj.magic x79);
                 Ojs.array_set x86 1 (Promise.t_to_js Obj.magic x80);
                 Ojs.array_set x86 2 (Promise.t_to_js Obj.magic x81);
                 Ojs.array_set x86 3 (Promise.t_to_js Obj.magic x82);
                 Ojs.array_set x86 4 (Promise.t_to_js Obj.magic x83);
                 Ojs.array_set x86 5 (Promise.t_to_js Obj.magic x84);
                 Ojs.array_set x86 6 (Promise.t_to_js Obj.magic x85);
                 x86))|])
    let (all6 :
      ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t * 'T5
        Promise.t * 'T6 Promise.t) ->
        ('T1 * 'T2 * 'T3 * 'T4 * 'T5 * 'T6) Promise.t)
      =
      fun
        (x96 :
          ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t *
            'T5 Promise.t * 'T6 Promise.t))
        ->
        Promise.t_of_js
          (fun (x110 : Ojs.t) ->
             let x111 = x110 in
             ((Obj.magic (Ojs.array_get x111 0)),
               (Obj.magic (Ojs.array_get x111 1)),
               (Obj.magic (Ojs.array_get x111 2)),
               (Obj.magic (Ojs.array_get x111 3)),
               (Obj.magic (Ojs.array_get x111 4)),
               (Obj.magic (Ojs.array_get x111 5))))
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "all"
             [|((let (x97, x98, x99, x100, x101, x102) = x96 in
                 let x103 = Ojs.array_make 6 in
                 Ojs.array_set x103 0 (Promise.t_to_js Obj.magic x97);
                 Ojs.array_set x103 1 (Promise.t_to_js Obj.magic x98);
                 Ojs.array_set x103 2 (Promise.t_to_js Obj.magic x99);
                 Ojs.array_set x103 3 (Promise.t_to_js Obj.magic x100);
                 Ojs.array_set x103 4 (Promise.t_to_js Obj.magic x101);
                 Ojs.array_set x103 5 (Promise.t_to_js Obj.magic x102);
                 x103))|])
    let (all5 :
      ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t * 'T5
        Promise.t) -> ('T1 * 'T2 * 'T3 * 'T4 * 'T5) Promise.t)
      =
      fun
        (x112 :
          ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t *
            'T5 Promise.t))
        ->
        Promise.t_of_js
          (fun (x124 : Ojs.t) ->
             let x125 = x124 in
             ((Obj.magic (Ojs.array_get x125 0)),
               (Obj.magic (Ojs.array_get x125 1)),
               (Obj.magic (Ojs.array_get x125 2)),
               (Obj.magic (Ojs.array_get x125 3)),
               (Obj.magic (Ojs.array_get x125 4))))
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "all"
             [|((let (x113, x114, x115, x116, x117) = x112 in
                 let x118 = Ojs.array_make 5 in
                 Ojs.array_set x118 0 (Promise.t_to_js Obj.magic x113);
                 Ojs.array_set x118 1 (Promise.t_to_js Obj.magic x114);
                 Ojs.array_set x118 2 (Promise.t_to_js Obj.magic x115);
                 Ojs.array_set x118 3 (Promise.t_to_js Obj.magic x116);
                 Ojs.array_set x118 4 (Promise.t_to_js Obj.magic x117);
                 x118))|])
    let (all4 :
      ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t) ->
        ('T1 * 'T2 * 'T3 * 'T4) Promise.t)
      =
      fun
        (x126 :
          ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t))
        ->
        Promise.t_of_js
          (fun (x136 : Ojs.t) ->
             let x137 = x136 in
             ((Obj.magic (Ojs.array_get x137 0)),
               (Obj.magic (Ojs.array_get x137 1)),
               (Obj.magic (Ojs.array_get x137 2)),
               (Obj.magic (Ojs.array_get x137 3))))
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "all"
             [|((let (x127, x128, x129, x130) = x126 in
                 let x131 = Ojs.array_make 4 in
                 Ojs.array_set x131 0 (Promise.t_to_js Obj.magic x127);
                 Ojs.array_set x131 1 (Promise.t_to_js Obj.magic x128);
                 Ojs.array_set x131 2 (Promise.t_to_js Obj.magic x129);
                 Ojs.array_set x131 3 (Promise.t_to_js Obj.magic x130);
                 x131))|])
    let (all3 :
      ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t) ->
        ('T1 * 'T2 * 'T3) Promise.t)
      =
      fun (x138 : ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t)) ->
        Promise.t_of_js
          (fun (x146 : Ojs.t) ->
             let x147 = x146 in
             ((Obj.magic (Ojs.array_get x147 0)),
               (Obj.magic (Ojs.array_get x147 1)),
               (Obj.magic (Ojs.array_get x147 2))))
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "all"
             [|((let (x139, x140, x141) = x138 in
                 let x142 = Ojs.array_make 3 in
                 Ojs.array_set x142 0 (Promise.t_to_js Obj.magic x139);
                 Ojs.array_set x142 1 (Promise.t_to_js Obj.magic x140);
                 Ojs.array_set x142 2 (Promise.t_to_js Obj.magic x141);
                 x142))|])
    let (all2 : ('T1 Promise.t * 'T2 Promise.t) -> ('T1 * 'T2) Promise.t) =
      fun (x148 : ('T1 Promise.t * 'T2 Promise.t)) ->
        Promise.t_of_js
          (fun (x154 : Ojs.t) ->
             let x155 = x154 in
             ((Obj.magic (Ojs.array_get x155 0)),
               (Obj.magic (Ojs.array_get x155 1))))
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "all"
             [|((let (x149, x150) = x148 in
                 let x151 = Ojs.array_make 2 in
                 Ojs.array_set x151 0 (Promise.t_to_js Obj.magic x149);
                 Ojs.array_set x151 1 (Promise.t_to_js Obj.magic x150);
                 x151))|])
    let (race : 'T list -> any Promise.t) =
      fun (x156 : 'T list) ->
        Promise.t_of_js any_of_js
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "race"
             [|(Ojs.list_to_js Obj.magic x156)|])
    let (reject : 'E -> 'T Promise.t) =
      fun (x159 : 'E) ->
        Promise.t_of_js Obj.magic
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "reject"
             [|(Obj.magic x159)|])
    let (resolve : 'T -> 'T Promise.t) =
      fun (x161 : 'T) ->
        Promise.t_of_js Obj.magic
          (Ojs.call (Ojs.get_prop_ascii Ojs.global "Promise") "resolve"
             [|(Obj.magic x161)|])
  end
module PromiseConstructor =
  struct
    type t = Ojs.t
    let rec t_of_js : Ojs.t -> t = fun (x164 : Ojs.t) -> x164
    and t_to_js : t -> Ojs.t = fun (x163 : Ojs.t) -> x163
    let (get_prototype : t -> any Promise.t) =
      fun (x165 : t) ->
        Promise.t_of_js any_of_js
          (Ojs.get_prop_ascii (t_to_js x165) "prototype")
    let (create :
      t ->
        (resolve:('T -> unit) -> reject:('E -> unit) -> unit) -> 'T Promise.t)
      =
      fun (x172 : t) ->
        fun (x167 : resolve:('T -> unit) -> reject:('E -> unit) -> unit) ->
          Promise.t_of_js Obj.magic
            (Ojs.new_obj (t_to_js x172)
               [|(Ojs.fun_to_js 2
                    (fun (x168 : Ojs.t) ->
                       fun (x170 : Ojs.t) ->
                         x167
                           ~resolve:(fun (x169 : 'T) ->
                                       ignore
                                         (Ojs.apply x168 [|(Obj.magic x169)|]))
                           ~reject:(fun (x171 : 'E) ->
                                      ignore
                                        (Ojs.apply x170 [|(Obj.magic x171)|]))))|])
    let (all : t -> 'T1 Promise.t list -> 'T1 list Promise.t) =
      fun (x177 : t) ->
        fun (x174 : 'T1 Promise.t list) ->
          Promise.t_of_js
            (fun (x178 : Ojs.t) -> Ojs.list_of_js Obj.magic x178)
            (Ojs.call (t_to_js x177) "all"
               [|(Ojs.list_to_js
                    (fun (x175 : 'T1 Promise.t) ->
                       Promise.t_to_js Obj.magic x175) x174)|])
    let (all10 :
      t ->
        ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t * 'T5
          Promise.t * 'T6 Promise.t * 'T7 Promise.t * 'T8 Promise.t * 'T9
          Promise.t * 'T10 Promise.t) ->
          ('T1 * 'T2 * 'T3 * 'T4 * 'T5 * 'T6 * 'T7 * 'T8 * 'T9 * 'T10)
            Promise.t)
      =
      fun (x202 : t) ->
        fun
          (x180 :
            ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t *
              'T5 Promise.t * 'T6 Promise.t * 'T7 Promise.t * 'T8 Promise.t *
              'T9 Promise.t * 'T10 Promise.t))
          ->
          Promise.t_of_js
            (fun (x203 : Ojs.t) ->
               let x204 = x203 in
               ((Obj.magic (Ojs.array_get x204 0)),
                 (Obj.magic (Ojs.array_get x204 1)),
                 (Obj.magic (Ojs.array_get x204 2)),
                 (Obj.magic (Ojs.array_get x204 3)),
                 (Obj.magic (Ojs.array_get x204 4)),
                 (Obj.magic (Ojs.array_get x204 5)),
                 (Obj.magic (Ojs.array_get x204 6)),
                 (Obj.magic (Ojs.array_get x204 7)),
                 (Obj.magic (Ojs.array_get x204 8)),
                 (Obj.magic (Ojs.array_get x204 9))))
            (Ojs.call (t_to_js x202) "all"
               [|((let (x181, x182, x183, x184, x185, x186, x187, x188, x189,
                        x190)
                     = x180 in
                   let x191 = Ojs.array_make 10 in
                   Ojs.array_set x191 0 (Promise.t_to_js Obj.magic x181);
                   Ojs.array_set x191 1 (Promise.t_to_js Obj.magic x182);
                   Ojs.array_set x191 2 (Promise.t_to_js Obj.magic x183);
                   Ojs.array_set x191 3 (Promise.t_to_js Obj.magic x184);
                   Ojs.array_set x191 4 (Promise.t_to_js Obj.magic x185);
                   Ojs.array_set x191 5 (Promise.t_to_js Obj.magic x186);
                   Ojs.array_set x191 6 (Promise.t_to_js Obj.magic x187);
                   Ojs.array_set x191 7 (Promise.t_to_js Obj.magic x188);
                   Ojs.array_set x191 8 (Promise.t_to_js Obj.magic x189);
                   Ojs.array_set x191 9 (Promise.t_to_js Obj.magic x190);
                   x191))|])
    let (all9 :
      t ->
        ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t * 'T5
          Promise.t * 'T6 Promise.t * 'T7 Promise.t * 'T8 Promise.t * 'T9
          Promise.t) ->
          ('T1 * 'T2 * 'T3 * 'T4 * 'T5 * 'T6 * 'T7 * 'T8 * 'T9) Promise.t)
      =
      fun (x225 : t) ->
        fun
          (x205 :
            ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t *
              'T5 Promise.t * 'T6 Promise.t * 'T7 Promise.t * 'T8 Promise.t *
              'T9 Promise.t))
          ->
          Promise.t_of_js
            (fun (x226 : Ojs.t) ->
               let x227 = x226 in
               ((Obj.magic (Ojs.array_get x227 0)),
                 (Obj.magic (Ojs.array_get x227 1)),
                 (Obj.magic (Ojs.array_get x227 2)),
                 (Obj.magic (Ojs.array_get x227 3)),
                 (Obj.magic (Ojs.array_get x227 4)),
                 (Obj.magic (Ojs.array_get x227 5)),
                 (Obj.magic (Ojs.array_get x227 6)),
                 (Obj.magic (Ojs.array_get x227 7)),
                 (Obj.magic (Ojs.array_get x227 8))))
            (Ojs.call (t_to_js x225) "all"
               [|((let (x206, x207, x208, x209, x210, x211, x212, x213, x214)
                     = x205 in
                   let x215 = Ojs.array_make 9 in
                   Ojs.array_set x215 0 (Promise.t_to_js Obj.magic x206);
                   Ojs.array_set x215 1 (Promise.t_to_js Obj.magic x207);
                   Ojs.array_set x215 2 (Promise.t_to_js Obj.magic x208);
                   Ojs.array_set x215 3 (Promise.t_to_js Obj.magic x209);
                   Ojs.array_set x215 4 (Promise.t_to_js Obj.magic x210);
                   Ojs.array_set x215 5 (Promise.t_to_js Obj.magic x211);
                   Ojs.array_set x215 6 (Promise.t_to_js Obj.magic x212);
                   Ojs.array_set x215 7 (Promise.t_to_js Obj.magic x213);
                   Ojs.array_set x215 8 (Promise.t_to_js Obj.magic x214);
                   x215))|])
    let (all8 :
      t ->
        ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t * 'T5
          Promise.t * 'T6 Promise.t * 'T7 Promise.t * 'T8 Promise.t) ->
          ('T1 * 'T2 * 'T3 * 'T4 * 'T5 * 'T6 * 'T7 * 'T8) Promise.t)
      =
      fun (x246 : t) ->
        fun
          (x228 :
            ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t *
              'T5 Promise.t * 'T6 Promise.t * 'T7 Promise.t * 'T8 Promise.t))
          ->
          Promise.t_of_js
            (fun (x247 : Ojs.t) ->
               let x248 = x247 in
               ((Obj.magic (Ojs.array_get x248 0)),
                 (Obj.magic (Ojs.array_get x248 1)),
                 (Obj.magic (Ojs.array_get x248 2)),
                 (Obj.magic (Ojs.array_get x248 3)),
                 (Obj.magic (Ojs.array_get x248 4)),
                 (Obj.magic (Ojs.array_get x248 5)),
                 (Obj.magic (Ojs.array_get x248 6)),
                 (Obj.magic (Ojs.array_get x248 7))))
            (Ojs.call (t_to_js x246) "all"
               [|((let (x229, x230, x231, x232, x233, x234, x235, x236) =
                     x228 in
                   let x237 = Ojs.array_make 8 in
                   Ojs.array_set x237 0 (Promise.t_to_js Obj.magic x229);
                   Ojs.array_set x237 1 (Promise.t_to_js Obj.magic x230);
                   Ojs.array_set x237 2 (Promise.t_to_js Obj.magic x231);
                   Ojs.array_set x237 3 (Promise.t_to_js Obj.magic x232);
                   Ojs.array_set x237 4 (Promise.t_to_js Obj.magic x233);
                   Ojs.array_set x237 5 (Promise.t_to_js Obj.magic x234);
                   Ojs.array_set x237 6 (Promise.t_to_js Obj.magic x235);
                   Ojs.array_set x237 7 (Promise.t_to_js Obj.magic x236);
                   x237))|])
    let (all7 :
      t ->
        ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t * 'T5
          Promise.t * 'T6 Promise.t * 'T7 Promise.t) ->
          ('T1 * 'T2 * 'T3 * 'T4 * 'T5 * 'T6 * 'T7) Promise.t)
      =
      fun (x265 : t) ->
        fun
          (x249 :
            ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t *
              'T5 Promise.t * 'T6 Promise.t * 'T7 Promise.t))
          ->
          Promise.t_of_js
            (fun (x266 : Ojs.t) ->
               let x267 = x266 in
               ((Obj.magic (Ojs.array_get x267 0)),
                 (Obj.magic (Ojs.array_get x267 1)),
                 (Obj.magic (Ojs.array_get x267 2)),
                 (Obj.magic (Ojs.array_get x267 3)),
                 (Obj.magic (Ojs.array_get x267 4)),
                 (Obj.magic (Ojs.array_get x267 5)),
                 (Obj.magic (Ojs.array_get x267 6))))
            (Ojs.call (t_to_js x265) "all"
               [|((let (x250, x251, x252, x253, x254, x255, x256) = x249 in
                   let x257 = Ojs.array_make 7 in
                   Ojs.array_set x257 0 (Promise.t_to_js Obj.magic x250);
                   Ojs.array_set x257 1 (Promise.t_to_js Obj.magic x251);
                   Ojs.array_set x257 2 (Promise.t_to_js Obj.magic x252);
                   Ojs.array_set x257 3 (Promise.t_to_js Obj.magic x253);
                   Ojs.array_set x257 4 (Promise.t_to_js Obj.magic x254);
                   Ojs.array_set x257 5 (Promise.t_to_js Obj.magic x255);
                   Ojs.array_set x257 6 (Promise.t_to_js Obj.magic x256);
                   x257))|])
    let (all6 :
      t ->
        ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t * 'T5
          Promise.t * 'T6 Promise.t) ->
          ('T1 * 'T2 * 'T3 * 'T4 * 'T5 * 'T6) Promise.t)
      =
      fun (x282 : t) ->
        fun
          (x268 :
            ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t *
              'T5 Promise.t * 'T6 Promise.t))
          ->
          Promise.t_of_js
            (fun (x283 : Ojs.t) ->
               let x284 = x283 in
               ((Obj.magic (Ojs.array_get x284 0)),
                 (Obj.magic (Ojs.array_get x284 1)),
                 (Obj.magic (Ojs.array_get x284 2)),
                 (Obj.magic (Ojs.array_get x284 3)),
                 (Obj.magic (Ojs.array_get x284 4)),
                 (Obj.magic (Ojs.array_get x284 5))))
            (Ojs.call (t_to_js x282) "all"
               [|((let (x269, x270, x271, x272, x273, x274) = x268 in
                   let x275 = Ojs.array_make 6 in
                   Ojs.array_set x275 0 (Promise.t_to_js Obj.magic x269);
                   Ojs.array_set x275 1 (Promise.t_to_js Obj.magic x270);
                   Ojs.array_set x275 2 (Promise.t_to_js Obj.magic x271);
                   Ojs.array_set x275 3 (Promise.t_to_js Obj.magic x272);
                   Ojs.array_set x275 4 (Promise.t_to_js Obj.magic x273);
                   Ojs.array_set x275 5 (Promise.t_to_js Obj.magic x274);
                   x275))|])
    let (all5 :
      t ->
        ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t * 'T5
          Promise.t) -> ('T1 * 'T2 * 'T3 * 'T4 * 'T5) Promise.t)
      =
      fun (x297 : t) ->
        fun
          (x285 :
            ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t *
              'T5 Promise.t))
          ->
          Promise.t_of_js
            (fun (x298 : Ojs.t) ->
               let x299 = x298 in
               ((Obj.magic (Ojs.array_get x299 0)),
                 (Obj.magic (Ojs.array_get x299 1)),
                 (Obj.magic (Ojs.array_get x299 2)),
                 (Obj.magic (Ojs.array_get x299 3)),
                 (Obj.magic (Ojs.array_get x299 4))))
            (Ojs.call (t_to_js x297) "all"
               [|((let (x286, x287, x288, x289, x290) = x285 in
                   let x291 = Ojs.array_make 5 in
                   Ojs.array_set x291 0 (Promise.t_to_js Obj.magic x286);
                   Ojs.array_set x291 1 (Promise.t_to_js Obj.magic x287);
                   Ojs.array_set x291 2 (Promise.t_to_js Obj.magic x288);
                   Ojs.array_set x291 3 (Promise.t_to_js Obj.magic x289);
                   Ojs.array_set x291 4 (Promise.t_to_js Obj.magic x290);
                   x291))|])
    let (all4 :
      t ->
        ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t) ->
          ('T1 * 'T2 * 'T3 * 'T4) Promise.t)
      =
      fun (x310 : t) ->
        fun
          (x300 :
            ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t * 'T4 Promise.t))
          ->
          Promise.t_of_js
            (fun (x311 : Ojs.t) ->
               let x312 = x311 in
               ((Obj.magic (Ojs.array_get x312 0)),
                 (Obj.magic (Ojs.array_get x312 1)),
                 (Obj.magic (Ojs.array_get x312 2)),
                 (Obj.magic (Ojs.array_get x312 3))))
            (Ojs.call (t_to_js x310) "all"
               [|((let (x301, x302, x303, x304) = x300 in
                   let x305 = Ojs.array_make 4 in
                   Ojs.array_set x305 0 (Promise.t_to_js Obj.magic x301);
                   Ojs.array_set x305 1 (Promise.t_to_js Obj.magic x302);
                   Ojs.array_set x305 2 (Promise.t_to_js Obj.magic x303);
                   Ojs.array_set x305 3 (Promise.t_to_js Obj.magic x304);
                   x305))|])
    let (all3 :
      t ->
        ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t) ->
          ('T1 * 'T2 * 'T3) Promise.t)
      =
      fun (x321 : t) ->
        fun (x313 : ('T1 Promise.t * 'T2 Promise.t * 'T3 Promise.t)) ->
          Promise.t_of_js
            (fun (x322 : Ojs.t) ->
               let x323 = x322 in
               ((Obj.magic (Ojs.array_get x323 0)),
                 (Obj.magic (Ojs.array_get x323 1)),
                 (Obj.magic (Ojs.array_get x323 2))))
            (Ojs.call (t_to_js x321) "all"
               [|((let (x314, x315, x316) = x313 in
                   let x317 = Ojs.array_make 3 in
                   Ojs.array_set x317 0 (Promise.t_to_js Obj.magic x314);
                   Ojs.array_set x317 1 (Promise.t_to_js Obj.magic x315);
                   Ojs.array_set x317 2 (Promise.t_to_js Obj.magic x316);
                   x317))|])
    let (all2 :
      t -> ('T1 Promise.t * 'T2 Promise.t) -> ('T1 * 'T2) Promise.t) =
      fun (x330 : t) ->
        fun (x324 : ('T1 Promise.t * 'T2 Promise.t)) ->
          Promise.t_of_js
            (fun (x331 : Ojs.t) ->
               let x332 = x331 in
               ((Obj.magic (Ojs.array_get x332 0)),
                 (Obj.magic (Ojs.array_get x332 1))))
            (Ojs.call (t_to_js x330) "all"
               [|((let (x325, x326) = x324 in
                   let x327 = Ojs.array_make 2 in
                   Ojs.array_set x327 0 (Promise.t_to_js Obj.magic x325);
                   Ojs.array_set x327 1 (Promise.t_to_js Obj.magic x326);
                   x327))|])
    let (all1 : t -> 'T Promise.t list -> 'T list Promise.t) =
      fun (x336 : t) ->
        fun (x333 : 'T Promise.t list) ->
          Promise.t_of_js
            (fun (x337 : Ojs.t) -> Ojs.list_of_js Obj.magic x337)
            (Ojs.call (t_to_js x336) "all"
               [|(Ojs.list_to_js
                    (fun (x334 : 'T Promise.t) ->
                       Promise.t_to_js Obj.magic x334) x333)|])
    let (race : t -> 'T list -> any Promise.t) =
      fun (x341 : t) ->
        fun (x339 : 'T list) ->
          Promise.t_of_js any_of_js
            (Ojs.call (t_to_js x341) "race"
               [|(Ojs.list_to_js Obj.magic x339)|])
    let (reject : t -> 'E -> 'T Promise.t) =
      fun (x344 : t) ->
        fun (x343 : 'E) ->
          Promise.t_of_js Obj.magic
            (Ojs.call (t_to_js x344) "reject" [|(Obj.magic x343)|])
    let (resolve : t -> unit Promise.t) =
      fun (x346 : t) ->
        Promise.t_of_js Ojs.unit_of_js
          (Ojs.call (t_to_js x346) "resolve" [||])
    let (resolve' : t -> 'T -> 'T Promise.t) =
      fun (x349 : t) ->
        fun (x348 : 'T) ->
          Promise.t_of_js Obj.magic
            (Ojs.call (t_to_js x349) "resolve" [|(Obj.magic x348)|])
  end
let (promise : PromiseConstructor.t) =
  PromiseConstructor.t_of_js (Ojs.get_prop_ascii Ojs.global "Promise")
