[@@@js.dummy "!! This code has been generated by gen_js_api !!"]
[@@@ocaml.warning "-7-32-39"]
[@@@ocaml.warning "-7-11-32-33-39"]
open Es2018
module Internal =
  struct
    module AnonymousInterfaces = struct  end
    module Types =
      struct
        open AnonymousInterfaces
        type _Symbol = symbol
        let rec _Symbol_of_js : Ojs.t -> _Symbol =
          fun (x2 : Ojs.t) -> symbol_of_js x2
        and _Symbol_to_js : _Symbol -> Ojs.t =
          fun (x1 : symbol) -> symbol_to_js x1
      end
  end
open Internal
open AnonymousInterfaces
open Types
module Symbol =
  struct
    type t = _Symbol
    let rec t_of_js : Ojs.t -> t = fun (x4 : Ojs.t) -> _Symbol_of_js x4
    and t_to_js : t -> Ojs.t = fun (x3 : _Symbol) -> _Symbol_to_js x3
    let (get_description : t -> string or_undefined) =
      fun (x5 : t) ->
        or_undefined_of_js Ojs.string_of_js
          (Ojs.get_prop_ascii (t_to_js x5) "description")
  end
